### ISSUE TITLE
Blueprint crashes while opening wallpapers from wallpapers tab on android 5.0

### ISSUE THREAD

**Issue by Gowsky** [jahirfiquitiva/Blueprint#84] opened 2018-05-22 11:25 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.7  & 1.1.5`
 - Android version: `5.0`
 - Device Manufacturer: `Various`
 - Device Name: `AVD Emulator AOSP, P6, Idol 3, ZenFone 2, Galaxy Alpha, Galaxy Note 3, Canvas Unite 2, K920/Vibe, Galaxy S4, Glade V6, Cloud Power+, x98air3g, Canvas Fire 4, C1AE-2, Redmi Note, ZenFone 2 Laser, Galaxy Tab A, LG Leon, Galaxy Note 3`

```Gradle
java.lang.NullPointerException: 
  at android.view.ViewOverlay$OverlayViewGroup.add (ViewOverlay.java:164)
  at android.view.ViewGroupOverlay.add (ViewGroupOverlay.java:63)
  at android.app.EnterTransitionCoordinator.startRejectedAnimations (EnterTransitionCoordinator.java:598)
  at android.app.EnterTransitionCoordinator.startSharedElementTransition (EnterTransitionCoordinator.java:325)
  at android.app.EnterTransitionCoordinator.access$200 (EnterTransitionCoordinator.java:42)
  at android.app.EnterTransitionCoordinator$5$1.run (EnterTransitionCoordinator.java:389)
  at android.app.ActivityTransitionCoordinator.startTransition (ActivityTransitionCoordinator.java:698)
  at android.app.EnterTransitionCoordinator$5.onPreDraw (EnterTransitionCoordinator.java:386)
  at android.view.ViewTreeObserver.dispatchOnPreDraw (ViewTreeObserver.java:847)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2294)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1251)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6438)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:795)
  at android.view.Choreographer.doCallbacks (Choreographer.java:598)
  at android.view.Choreographer.doFrame (Choreographer.java:567)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:781)
  at android.os.Handler.handleCallback (Handler.java:810)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:189)
  at android.app.ActivityThread.main (ActivityThread.java:5529)
  at java.lang.reflect.Method.invoke (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:950)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:745)
```

### Reproduction Steps

1. Open any wallpaper from wallpapers tab

### Expected Result
Wallpaper view opens

### Actual Result
App crashes

**Comment by jahirfiquitiva** [comment] 2018-05-22 19:11
Please specify the Various manufacturers. And does this for sure only happens in Android 5.0

**Comment by Gowsky** [comment] 2018-05-22 19:45
Yes, it happens only on Android 5.0

**Comment by Gowsky** [comment] 2018-06-03 14:39
Issue still occurs in BP 1.1.8

**Comment by jahirfiquitiva** [comment] 2018-06-03 15:04
@Gowsky Do you have logs that actually mention `jahirfiquitiva.libs.blueprint` somewhere? It's hard to track where the issue is occurring without them

**Comment by jahirfiquitiva** [comment] 2018-06-03 16:14
I'm closing this. Already tested in an Android 5.0 device and it's working now

**Closed by jahirfiquitiva** 2018-06-03 16:14 UTC
Labels: Priority: High, Status: Accepted, Type: Bug
