### ISSUE TITLE
Licence not valid on any release build

### ISSUE THREAD

**Issue by JustMeErazem** [jahirfiquitiva/Blueprint#107] opened 2018-07-24 18:15 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `1.2.5`
 - Android version: `8.1`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Redmi Note 3`

### Describe the bug
Every time the app is compiles and signed (release), the license is not valid (message: You shall not pass!), even if Lucky Patcher and Store verification is off.

### Reproduction Steps
1. Build signed APK
2. Install on device
3. Open app

### Expected behavior
App would let me do stuff.

### Additional context
Could it be that I am using the F-Droid store?

**Comment by jahirfiquitiva** [comment] 2018-07-24 18:18
1. Please show me a screenshot of the dialog you get
2. If you enabled Google license check, it will only allow installations from Google Play Store

**Comment by JustMeErazem** [comment] 2018-07-24 18:22
```
override fun amazonInstallsEnabled(): Boolean = false
override fun checkLPF(): Boolean = false
override fun checkStores(): Boolean = false
```
They are all disabled.

![screenshot_blueprint_20180724-201926](https://user-images.githubusercontent.com/26996616/43158157-479b3012-8f7f-11e8-8627-ad14f970d336.png)

This is the error message I get.

**Comment by jahirfiquitiva** [comment] 2018-07-24 18:23
Did you add the Google license key to the app?

**Comment by JustMeErazem** [comment] 2018-07-24 18:23
No, I wanted to only distribute it on F-Droid.

**Comment by jahirfiquitiva** [comment] 2018-07-24 18:29
Try replacing this: 
```kotlin
override fun getLicKey(): String? = 
"MIIBIjANBgkqhkiGgKglYGYGihLuihUuhhuBlouBkuiu"
```

With this:
```kotlin
override fun getLicKey(): String? = ""
```

**Comment by JustMeErazem** [comment] 2018-07-24 18:32
I still get the same error.

**Comment by jahirfiquitiva** [comment] 2018-07-24 18:34
@JustMeErazem 
Ok, then the error might be because of installing from F-Droid

Please kindly wait a few days for me to get this fixed properly

**Comment by JustMeErazem** [comment] 2018-07-24 18:36
Ok no problem, thank you. My installing from F-Droid you mean because I have F-Droid installed, right? Because I haven't actually downloaded it from F-Droid, only compiled it.

**Comment by jahirfiquitiva** [comment] 2018-07-24 18:36
@JustMeErazem 
I will close this issue in favor of a [more specific one](https://github.com/jahirfiquitiva/Blueprint/issues/108)

**Comment by jahirfiquitiva** [comment] 2018-07-24 18:42
> Ok no problem, thank you. My installing from F-Droid you mean because I have F-Droid installed, right? Because I haven't actually downloaded it from F-Droid, only compiled it.

@JustMeErazem So you didn't download it from F-Droid? 

Then the issue is much simpler.

When you create a debug build of the app, the license check is not enabled. But since you are generating a signed apk ready for release, the license check is enabled

So, for testing, always use debug apks, or easier: the run button inside Android Studio.

**Comment by JustMeErazem** [comment] 2018-07-24 18:44
But won't the problem appear again if I or other users want to later download the app after uploading it to F-Droid?

**Comment by jahirfiquitiva** [comment] 2018-07-24 18:45
@JustMeErazem I haven't tested installations from F-Droid, so the issue #108 still applies and I'd have to test it.

Just wanted to let you know why the license check was invalid for you

**Comment by JustMeErazem** [comment] 2018-07-24 18:45
Ok thank you very much.

**Closed** 2018-07-24 18:45 UTC
Labels: Priority: Low, Status: Accepted, Type: Question

**Comment by jahirfiquitiva** [comment] 2018-07-24 19:34
@JustMeErazem 

I won't test the F-Droid publishing process because it seems overcomplicated, and I don't really have enough time to do that.

Anyways, since you are basically disabling all the license checks already, you can disable it completely (it will allow all installs from anywhere) by doing this:

Replace:
```kotlin
   override fun getLicenseChecker(): PiracyChecker? {
        destroyChecker() // Important
        return if (BuildConfig.DEBUG) null
        else super.getLicenseChecker()
    }
```

With:
```kotlin
   override fun getLicenseChecker(): PiracyChecker? {
        destroyChecker() // Important
        return null
    }
```

**Comment by JustMeErazem** [comment] 2018-07-24 19:41
Thank you and no problem, I wanted it to stay open source, so there really is no need for a licence checker.

**Comment by jahirfiquitiva** [comment] 2018-07-24 19:42
@JustMeErazem That's great! So, yeah, you can disable it as I mentioned before 😀
